OCAMLMAKEFILE = OCamlMakefile

SOURCES = remodel_ast.ml remodel_parse.mly remodel_lex.mll remodel.ml
RESULT = remodel
PACKS = extlib unix parmap
OCAMLLDFLAGS = -g
YFLAGS = -v


include $(OCAMLMAKEFILE)

